// Mocks generated by Mockito 5.4.6 from annotations
// in pscommunitymobileapp/test/features/payment/presentation/controllers/payment_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:pscommunitymobileapp/core/errors/failures.dart' as _i9;
import 'package:pscommunitymobileapp/core/network/api_response.dart' as _i10;
import 'package:pscommunitymobileapp/features/payment/domain/entities/payment_category.dart'
    as _i8;
import 'package:pscommunitymobileapp/features/payment/domain/entities/payment_dashboard.dart'
    as _i2;
import 'package:pscommunitymobileapp/features/payment/domain/entities/payment_item.dart'
    as _i11;
import 'package:pscommunitymobileapp/features/payment/domain/entities/payment_mode.dart'
    as _i6;
import 'package:pscommunitymobileapp/features/payment/domain/entities/payment_type.dart'
    as _i7;
import 'package:pscommunitymobileapp/features/payment/domain/entities/razorpay_order.dart'
    as _i3;
import 'package:pscommunitymobileapp/features/payment/domain/repositories/payment_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaymentDashboard_0 extends _i1.SmartFake
    implements _i2.PaymentDashboard {
  _FakePaymentDashboard_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRazorpayOrder_1 extends _i1.SmartFake implements _i3.RazorpayOrder {
  _FakeRazorpayOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i4.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<Map<String, dynamic>>> getPaymentStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentStatuses, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i2.PaymentDashboard> getDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, []),
            returnValue: _i5.Future<_i2.PaymentDashboard>.value(
              _FakePaymentDashboard_0(
                this,
                Invocation.method(#getDashboard, []),
              ),
            ),
          )
          as _i5.Future<_i2.PaymentDashboard>);

  @override
  _i5.Future<List<_i6.PaymentMode>> getPaymentModes() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentModes, []),
            returnValue: _i5.Future<List<_i6.PaymentMode>>.value(
              <_i6.PaymentMode>[],
            ),
          )
          as _i5.Future<List<_i6.PaymentMode>>);

  @override
  _i5.Future<List<_i7.PaymentType>> getPaymentTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentTypes, []),
            returnValue: _i5.Future<List<_i7.PaymentType>>.value(
              <_i7.PaymentType>[],
            ),
          )
          as _i5.Future<List<_i7.PaymentType>>);

  @override
  _i5.Future<List<_i8.PaymentCategory>> getCategories(int? paymentTypeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [paymentTypeId]),
            returnValue: _i5.Future<List<_i8.PaymentCategory>>.value(
              <_i8.PaymentCategory>[],
            ),
          )
          as _i5.Future<List<_i8.PaymentCategory>>);

  @override
  _i5.Future<_i3.RazorpayOrder> createOrder({
    required double? amount,
    required int? paymentTypeId,
    required int? paymentCategoryId,
    int? adminPaymentRequestId,
    String? currency = 'INR',
    int? memberId = 0,
    int? paymentStatusId = 0,
    int? paymentModeId = 0,
    String? description,
    bool? isRecurring = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #amount: amount,
              #paymentTypeId: paymentTypeId,
              #paymentCategoryId: paymentCategoryId,
              #adminPaymentRequestId: adminPaymentRequestId,
              #currency: currency,
              #memberId: memberId,
              #paymentStatusId: paymentStatusId,
              #paymentModeId: paymentModeId,
              #description: description,
              #isRecurring: isRecurring,
            }),
            returnValue: _i5.Future<_i3.RazorpayOrder>.value(
              _FakeRazorpayOrder_1(
                this,
                Invocation.method(#createOrder, [], {
                  #amount: amount,
                  #paymentTypeId: paymentTypeId,
                  #paymentCategoryId: paymentCategoryId,
                  #adminPaymentRequestId: adminPaymentRequestId,
                  #currency: currency,
                  #memberId: memberId,
                  #paymentStatusId: paymentStatusId,
                  #paymentModeId: paymentModeId,
                  #description: description,
                  #isRecurring: isRecurring,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RazorpayOrder>);

  @override
  _i5.Future<Map<String, dynamic>> verifyPayment({
    required String? razorpayOrderId,
    required String? razorpayPaymentId,
    required String? razorpaySignature,
    required double? amount,
    required int? paymentTypeId,
    required int? paymentCategoryId,
    int? adminPaymentRequestId,
    bool? isRecurring = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPayment, [], {
              #razorpayOrderId: razorpayOrderId,
              #razorpayPaymentId: razorpayPaymentId,
              #razorpaySignature: razorpaySignature,
              #amount: amount,
              #paymentTypeId: paymentTypeId,
              #paymentCategoryId: paymentCategoryId,
              #adminPaymentRequestId: adminPaymentRequestId,
              #isRecurring: isRecurring,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i9.Result<_i10.PaginatedResponse<_i11.PaymentItem>>> getHistory({
    int? page = 1,
    int? pageSize = 20,
    int? paymentTypeId,
    int? categoryId,
    int? year,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, [], {
              #page: page,
              #pageSize: pageSize,
              #paymentTypeId: paymentTypeId,
              #categoryId: categoryId,
              #year: year,
              #status: status,
            }),
            returnValue:
                _i5.Future<
                  _i9.Result<_i10.PaginatedResponse<_i11.PaymentItem>>
                >.value(
                  _i12.dummyValue<
                    _i9.Result<_i10.PaginatedResponse<_i11.PaymentItem>>
                  >(
                    this,
                    Invocation.method(#getHistory, [], {
                      #page: page,
                      #pageSize: pageSize,
                      #paymentTypeId: paymentTypeId,
                      #categoryId: categoryId,
                      #year: year,
                      #status: status,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i9.Result<_i10.PaginatedResponse<_i11.PaymentItem>>>);

  @override
  _i5.Future<Map<String, dynamic>> getReceipt(int? receiptId) =>
      (super.noSuchMethod(
            Invocation.method(#getReceipt, [receiptId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
