// Mocks generated by Mockito 5.4.6 from annotations
// in pscommunitymobileapp/test/core/auth/auth_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pscommunitymobileapp/core/localization/localization_service.dart'
    as _i5;
import 'package:pscommunitymobileapp/core/localization/models/language.dart'
    as _i7;
import 'package:pscommunitymobileapp/core/storage/token_manager.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRx_0<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_1<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenManager extends _i1.Mock implements _i3.TokenManager {
  @override
  _i2.Rx<_i3.TokenPair> get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _FakeRx_0<_i3.TokenPair>(
              this,
              Invocation.getter(#authState),
            ),
            returnValueForMissingStub: _FakeRx_0<_i3.TokenPair>(
              this,
              Invocation.getter(#authState),
            ),
          )
          as _i2.Rx<_i3.TokenPair>);

  @override
  _i4.Stream<bool> get isLoggedInStream =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedInStream),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  bool get hasToken =>
      (super.noSuchMethod(
            Invocation.getter(#hasToken),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasValidAccessToken =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidAccessToken),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasValidToken =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidToken),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#hasRefreshToken),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDefaultPassword =>
      (super.noSuchMethod(
            Invocation.getter(#isDefaultPassword),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAccessTokenExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isAccessTokenExpired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i3.TokenPair> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i4.Stream<_i3.TokenPair>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.TokenPair>.empty(),
          )
          as _i4.Stream<_i3.TokenPair>);

  @override
  _i4.Future<void> bootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#bootstrap, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveTokens(
    String? access,
    String? refresh, {
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveTokens,
              [access, refresh],
              {#isDefault: isDefault},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LocalizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationService extends _i1.Mock
    implements _i5.LocalizationService {
  @override
  _i2.Rx<_i6.Locale> get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeRx_0<_i6.Locale>(
              this,
              Invocation.getter(#currentLocale),
            ),
            returnValueForMissingStub: _FakeRx_0<_i6.Locale>(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as _i2.Rx<_i6.Locale>);

  @override
  _i2.RxList<_i7.Language> get languages =>
      (super.noSuchMethod(
            Invocation.getter(#languages),
            returnValue: _FakeRxList_1<_i7.Language>(
              this,
              Invocation.getter(#languages),
            ),
            returnValueForMissingStub: _FakeRxList_1<_i7.Language>(
              this,
              Invocation.getter(#languages),
            ),
          )
          as _i2.RxList<_i7.Language>);

  @override
  Map<String, Map<String, String>> get keys =>
      (super.noSuchMethod(
            Invocation.getter(#keys),
            returnValue: <String, Map<String, String>>{},
            returnValueForMissingStub: <String, Map<String, String>>{},
          )
          as Map<String, Map<String, String>>);

  @override
  set keys(Map<String, Map<String, String>>? value) => super.noSuchMethod(
    Invocation.setter(#keys, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> bootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#bootstrap, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> fetchLanguages() =>
      (super.noSuchMethod(
            Invocation.method(#fetchLanguages, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changeLocale(String? langCode, String? countryCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocale, [langCode, countryCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
